/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as crownFundingSol from "./CrownFunding.sol";
export type { crownFundingSol };
import type * as eventsSol from "./Events.sol";
export type { eventsSol };
import type * as fixedArraySol from "./FixedArray.sol";
export type { fixedArraySol };
import type * as functionModifierSol from "./FunctionModifier.sol";
export type { functionModifierSol };
import type * as inheritanceSol from "./Inheritance.sol";
export type { inheritanceSol };
import type * as instructorSol from "./Instructor.sol";
export type { instructorSol };
import type * as mappingSol from "./Mapping.sol";
export type { mappingSol };
import type * as visibilitySol from "./Visibility.sol";
export type { visibilitySol };
import type * as myconstractSol from "./myconstract.sol";
export type { myconstractSol };
export type { Auction } from "./Auction";
export type { BytesAndStrings } from "./BytesAndStrings";
export type { Deposit } from "./Deposit";
export type { DynamicArrays } from "./DynamicArrays";
export type { GettersSetters } from "./GettersSetters";
export type { GlobalVariables } from "./GlobalVariables";
export type { Lottery } from "./Lottery";
export type { MyToken } from "./MyToken";
export type { StateVariables } from "./StateVariables";
