/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface SchoolInterface extends utils.Interface {
  functions: {
    "schoolInstructor()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "schoolInstructor"): FunctionFragment;

  encodeFunctionData(
    functionFragment: "schoolInstructor",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "schoolInstructor",
    data: BytesLike
  ): Result;

  events: {};
}

export interface School extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: SchoolInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    schoolInstructor(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        age: BigNumber;
        name: string;
        addr: string;
      }
    >;
  };

  schoolInstructor(
    overrides?: CallOverrides
  ): Promise<
    [BigNumber, string, string] & { age: BigNumber; name: string; addr: string }
  >;

  callStatic: {
    schoolInstructor(
      overrides?: CallOverrides
    ): Promise<
      [BigNumber, string, string] & {
        age: BigNumber;
        name: string;
        addr: string;
      }
    >;
  };

  filters: {};

  estimateGas: {
    schoolInstructor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    schoolInstructor(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
