/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { B, BInterface } from "../B";

const _abi = [
  {
    inputs: [],
    name: "f2",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "f4",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "f5",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getY",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "x",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "xx",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052600a600055601460015561001c61003160201b60201c565b60025534801561002b57600080fd5b5061003a565b60008054905090565b6101c6806100496000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80630b7f1665146100675780630c55699c146100855780633c9d377d146100a35780639942ec6f146100c1578063c3f90202146100df578063ece57b04146100fd575b600080fd5b61006f61011b565b60405161007c919061016b565b60405180910390f35b61008d610125565b60405161009a919061016b565b60405180910390f35b6100ab61012b565b6040516100b8919061016b565b60405180910390f35b6100c9610130565b6040516100d6919061016b565b60405180910390f35b6100e7610144565b6040516100f4919061016b565b60405180910390f35b61010561014d565b604051610112919061016b565b60405180910390f35b6000600154905090565b60005481565b600090565b60008061013b610153565b90508091505090565b60008054905090565b60025481565b60008054905090565b61016581610186565b82525050565b6000602082019050610180600083018461015c565b92915050565b600081905091905056fea264697066735822122044f098f4158538352ba1e4f2644ce5618d6bc8a081f5722d1dff61d4aec21d5d64736f6c63430008040033";

export class B__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<B> {
    return super.deploy(overrides || {}) as Promise<B>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): B {
    return super.attach(address) as B;
  }
  connect(signer: Signer): B__factory {
    return super.connect(signer) as B__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BInterface {
    return new utils.Interface(_abi) as BInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): B {
    return new Contract(address, _abi, signerOrProvider) as B;
  }
}
