/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Property, PropertyInterface } from "../Property";

const _abi = [
  {
    inputs: [],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_owner",
        type: "address",
      },
    ],
    name: "changeOwner",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "owner",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "price",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_price",
        type: "uint256",
      },
    ],
    name: "setPrice",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b506000808190555033600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff160217905550610363806100686000396000f3fe608060405234801561001057600080fd5b506004361061004c5760003560e01c80638da5cb5b1461005157806391b7f5ed1461006f578063a035b1fe1461008b578063a6f9dae1146100a9575b600080fd5b6100596100c5565b604051610066919061028d565b60405180910390f35b61008960048036038101906100849190610246565b6100eb565b005b61009361014f565b6040516100a091906102a8565b60405180910390f35b6100c360048036038101906100be919061021d565b610155565b005b600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1681565b3373ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff161461014557600080fd5b8060008190555050565b60005481565b3373ffffffffffffffffffffffffffffffffffffffff16600160009054906101000a900473ffffffffffffffffffffffffffffffffffffffff1673ffffffffffffffffffffffffffffffffffffffff16146101af57600080fd5b80600160006101000a81548173ffffffffffffffffffffffffffffffffffffffff021916908373ffffffffffffffffffffffffffffffffffffffff16021790555050565b600081359050610202816102ff565b92915050565b60008135905061021781610316565b92915050565b60006020828403121561022f57600080fd5b600061023d848285016101f3565b91505092915050565b60006020828403121561025857600080fd5b600061026684828501610208565b91505092915050565b610278816102c3565b82525050565b610287816102f5565b82525050565b60006020820190506102a2600083018461026f565b92915050565b60006020820190506102bd600083018461027e565b92915050565b60006102ce826102d5565b9050919050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b6000819050919050565b610308816102c3565b811461031357600080fd5b50565b61031f816102f5565b811461032a57600080fd5b5056fea26469706673582212200482c15dfaaef576dd25fc03a9d62874fa1dd378d8bddc321620bdb5ffcabd0964736f6c63430008040033";

export class Property__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Property> {
    return super.deploy(overrides || {}) as Promise<Property>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Property {
    return super.attach(address) as Property;
  }
  connect(signer: Signer): Property__factory {
    return super.connect(signer) as Property__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): PropertyInterface {
    return new utils.Interface(_abi) as PropertyInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): Property {
    return new Contract(address, _abi, signerOrProvider) as Property;
  }
}
