/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../../../common";
import type { B, BInterface } from "../../../contracts/Visibility.sol/B";

const _abi = [
  {
    inputs: [],
    name: "f2",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "f4",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "f5",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "pure",
    type: "function",
  },
  {
    inputs: [],
    name: "getY",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "x",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "xx",
    outputs: [
      {
        internalType: "int256",
        name: "",
        type: "int256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052600a600055601460015561001c61003160201b60201c565b60025534801561002b57600080fd5b5061003a565b60008054905090565b6101cb806100496000396000f3fe608060405234801561001057600080fd5b50600436106100625760003560e01c80630b7f1665146100675780630c55699c146100855780633c9d377d146100a35780639942ec6f146100c1578063c3f90202146100df578063ece57b04146100fd575b600080fd5b61006f61011b565b60405161007c919061017a565b60405180910390f35b61008d610125565b60405161009a919061017a565b60405180910390f35b6100ab61012b565b6040516100b8919061017a565b60405180910390f35b6100c9610135565b6040516100d6919061017a565b60405180910390f35b6100e7610149565b6040516100f4919061017a565b60405180910390f35b610105610152565b604051610112919061017a565b60405180910390f35b6000600154905090565b60005481565b6000808091505090565b600080610140610158565b90508091505090565b60008054905090565b60025481565b60008054905090565b6000819050919050565b61017481610161565b82525050565b600060208201905061018f600083018461016b565b9291505056fea2646970667358221220d59598a40d6ba0b3a04bef22c6a17254e444c016b94215ff0f0f725e97fe1f5b64736f6c634300080f0033";

type BConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: BConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class B__factory extends ContractFactory {
  constructor(...args: BConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<B> {
    return super.deploy(overrides || {}) as Promise<B>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): B {
    return super.attach(address) as B;
  }
  override connect(signer: Signer): B__factory {
    return super.connect(signer) as B__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): BInterface {
    return new utils.Interface(_abi) as BInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): B {
    return new Contract(address, _abi, signerOrProvider) as B;
  }
}
