/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as crownFundingSol from "./CrownFunding.sol";
export * as fixedArraySol from "./FixedArray.sol";
export * as functionModifierSol from "./FunctionModifier.sol";
export * as instructorSol from "./Instructor.sol";
export * as mappingSol from "./Mapping.sol";
export * as visibilitySol from "./Visibility.sol";
export * as myconstractSol from "./myconstract.sol";
export { Auction__factory } from "./Auction__factory";
export { BytesAndStrings__factory } from "./BytesAndStrings__factory";
export { Deposit__factory } from "./Deposit__factory";
export { DynamicArrays__factory } from "./DynamicArrays__factory";
export { GettersSetters__factory } from "./GettersSetters__factory";
export { GlobalVariables__factory } from "./GlobalVariables__factory";
export { Lottery__factory } from "./Lottery__factory";
export { MyToken__factory } from "./MyToken__factory";
export { StateVariables__factory } from "./StateVariables__factory";
