/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface AInterface extends utils.Interface {
  functions: {
    "f2()": FunctionFragment;
    "f4()": FunctionFragment;
    "f5()": FunctionFragment;
    "getY()": FunctionFragment;
    "x()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "f2" | "f4" | "f5" | "getY" | "x"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "f2", values?: undefined): string;
  encodeFunctionData(functionFragment: "f4", values?: undefined): string;
  encodeFunctionData(functionFragment: "f5", values?: undefined): string;
  encodeFunctionData(functionFragment: "getY", values?: undefined): string;
  encodeFunctionData(functionFragment: "x", values?: undefined): string;

  decodeFunctionResult(functionFragment: "f2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "f4", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "f5", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getY", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "x", data: BytesLike): Result;

  events: {};
}

export interface A extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: AInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    f2(overrides?: CallOverrides): Promise<[BigNumber]>;

    f4(overrides?: CallOverrides): Promise<[BigNumber]>;

    f5(overrides?: CallOverrides): Promise<[BigNumber]>;

    getY(overrides?: CallOverrides): Promise<[BigNumber]>;

    x(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  f2(overrides?: CallOverrides): Promise<BigNumber>;

  f4(overrides?: CallOverrides): Promise<BigNumber>;

  f5(overrides?: CallOverrides): Promise<BigNumber>;

  getY(overrides?: CallOverrides): Promise<BigNumber>;

  x(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    f2(overrides?: CallOverrides): Promise<BigNumber>;

    f4(overrides?: CallOverrides): Promise<BigNumber>;

    f5(overrides?: CallOverrides): Promise<BigNumber>;

    getY(overrides?: CallOverrides): Promise<BigNumber>;

    x(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    f2(overrides?: CallOverrides): Promise<BigNumber>;

    f4(overrides?: CallOverrides): Promise<BigNumber>;

    f5(overrides?: CallOverrides): Promise<BigNumber>;

    getY(overrides?: CallOverrides): Promise<BigNumber>;

    x(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    f2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    f4(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    f5(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getY(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    x(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
