/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface CInterface extends utils.Interface {
  functions: {
    "contractA()": FunctionFragment;
    "xx()": FunctionFragment;
  };

  getFunction(nameOrSignatureOrTopic: "contractA" | "xx"): FunctionFragment;

  encodeFunctionData(functionFragment: "contractA", values?: undefined): string;
  encodeFunctionData(functionFragment: "xx", values?: undefined): string;

  decodeFunctionResult(functionFragment: "contractA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "xx", data: BytesLike): Result;

  events: {};
}

export interface C extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: CInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    contractA(overrides?: CallOverrides): Promise<[string]>;

    xx(overrides?: CallOverrides): Promise<[BigNumber]>;
  };

  contractA(overrides?: CallOverrides): Promise<string>;

  xx(overrides?: CallOverrides): Promise<BigNumber>;

  callStatic: {
    contractA(overrides?: CallOverrides): Promise<string>;

    xx(overrides?: CallOverrides): Promise<BigNumber>;
  };

  filters: {};

  estimateGas: {
    contractA(overrides?: CallOverrides): Promise<BigNumber>;

    xx(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    contractA(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    xx(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
