/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Cryptos } from "./Cryptos";
export type { CryptosICO } from "./CryptosICO";
export type { ERC20Interface } from "./ERC20Interface";
