/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ERC20 } from "./ERC20";
export type { IERC20Metadata } from "./IERC20Metadata";
export type { IERC20 } from "./IERC20";
export type { BytesAndStrings } from "./BytesAndStrings";
export type { Deposit } from "./Deposit";
export type { DynamicArrays } from "./DynamicArrays";
export type { FixedSizeArray } from "./FixedSizeArray";
export type { GettersSetters } from "./GettersSetters";
export type { GlobalVariables } from "./GlobalVariables";
export type { Academy } from "./Academy";
export type { School } from "./School";
export type { Lottery } from "./Lottery";
export type { Auction } from "./Auction";
export type { Property } from "./Property";
export type { MyToken } from "./MyToken";
export type { StateVariables } from "./StateVariables";
export type { A } from "./A";
export type { B } from "./B";
export type { C } from "./C";

export { ERC20__factory } from "./factories/ERC20__factory";
export { IERC20Metadata__factory } from "./factories/IERC20Metadata__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
export { BytesAndStrings__factory } from "./factories/BytesAndStrings__factory";
export { Deposit__factory } from "./factories/Deposit__factory";
export { DynamicArrays__factory } from "./factories/DynamicArrays__factory";
export { FixedSizeArray__factory } from "./factories/FixedSizeArray__factory";
export { GettersSetters__factory } from "./factories/GettersSetters__factory";
export { GlobalVariables__factory } from "./factories/GlobalVariables__factory";
export { Academy__factory } from "./factories/Academy__factory";
export { School__factory } from "./factories/School__factory";
export { Lottery__factory } from "./factories/Lottery__factory";
export { Auction__factory } from "./factories/Auction__factory";
export { Property__factory } from "./factories/Property__factory";
export { MyToken__factory } from "./factories/MyToken__factory";
export { StateVariables__factory } from "./factories/StateVariables__factory";
export { A__factory } from "./factories/A__factory";
export { B__factory } from "./factories/B__factory";
export { C__factory } from "./factories/C__factory";
