/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "../../common";

export interface FixedSizeArrayInterface extends utils.Interface {
  functions: {
    "b1()": FunctionFragment;
    "b2()": FunctionFragment;
    "b3()": FunctionFragment;
    "getLength()": FunctionFragment;
    "numbers(uint256)": FunctionFragment;
    "setBytesArray()": FunctionFragment;
    "setElement(uint256,uint256)": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic:
      | "b1"
      | "b2"
      | "b3"
      | "getLength"
      | "numbers"
      | "setBytesArray"
      | "setElement"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "b1", values?: undefined): string;
  encodeFunctionData(functionFragment: "b2", values?: undefined): string;
  encodeFunctionData(functionFragment: "b3", values?: undefined): string;
  encodeFunctionData(functionFragment: "getLength", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "numbers",
    values: [PromiseOrValue<BigNumberish>]
  ): string;
  encodeFunctionData(
    functionFragment: "setBytesArray",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setElement",
    values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
  ): string;

  decodeFunctionResult(functionFragment: "b1", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "b2", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "b3", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getLength", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "numbers", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setBytesArray",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setElement", data: BytesLike): Result;

  events: {};
}

export interface FixedSizeArray extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: FixedSizeArrayInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    b1(overrides?: CallOverrides): Promise<[string]>;

    b2(overrides?: CallOverrides): Promise<[string]>;

    b3(overrides?: CallOverrides): Promise<[string]>;

    getLength(overrides?: CallOverrides): Promise<[BigNumber]>;

    numbers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<[BigNumber]>;

    setBytesArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    setElement(
      index: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;
  };

  b1(overrides?: CallOverrides): Promise<string>;

  b2(overrides?: CallOverrides): Promise<string>;

  b3(overrides?: CallOverrides): Promise<string>;

  getLength(overrides?: CallOverrides): Promise<BigNumber>;

  numbers(
    arg0: PromiseOrValue<BigNumberish>,
    overrides?: CallOverrides
  ): Promise<BigNumber>;

  setBytesArray(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  setElement(
    index: PromiseOrValue<BigNumberish>,
    value: PromiseOrValue<BigNumberish>,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    b1(overrides?: CallOverrides): Promise<string>;

    b2(overrides?: CallOverrides): Promise<string>;

    b3(overrides?: CallOverrides): Promise<string>;

    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    numbers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBytesArray(overrides?: CallOverrides): Promise<void>;

    setElement(
      index: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    b1(overrides?: CallOverrides): Promise<BigNumber>;

    b2(overrides?: CallOverrides): Promise<BigNumber>;

    b3(overrides?: CallOverrides): Promise<BigNumber>;

    getLength(overrides?: CallOverrides): Promise<BigNumber>;

    numbers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    setBytesArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    setElement(
      index: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    b1(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    b2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    b3(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    getLength(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    numbers(
      arg0: PromiseOrValue<BigNumberish>,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    setBytesArray(
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    setElement(
      index: PromiseOrValue<BigNumberish>,
      value: PromiseOrValue<BigNumberish>,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;
  };
}
